version: '3'
services:
  server:
    image: main:1.1
    container_name: flask-app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_ENV=development
    restart: always
  alarm:
    image: alarm:1.1
    container_name: alarm
    environment:
      - TELEGRAMM_TOKEN=${TELEGRAMM_TOKEN:-''}
    depends_on:
      - server
    volumes:
      - /srv/graf:/mnt
    restart: always
    