version: '3'
services:
  server:
    build: ./Dockerfile-main
    container_name: flask_app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_ENV=development
  alarm:
    build: ./Dockerfile-alarm
    container_name: alarm
    