version: '3'
services:
  server:
    image: main:1.1
    container_name: flask-app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_ENV=development
    restart: always

  alarm:
    image: alarm:1.1
    container_name: alarm
    environment:
      - TELEGRAMM_TOKEN=${TELEGRAMM_TOKEN}
    depends_on:
      - server
      - postgre
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - postgre

  postgre:
    image: postgres:alpine3.18
    container_name: postgre
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=lsd1lsd2
      - TZ="GMT+4"
      - PGTZ="GMT+4"
      # - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /srv/postgre/data:/var/lib/postgresql/data
      # - /srv/postgre/config/postgresql.conf.sample :/usr/local/share/postgresql/postgresql.conf.sample 

volumes:
  grafana-storage: {}
  # postgre: {}