version: '3'
services:
  server:
    image: main:1
    container_name: flask_app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_ENV=development
  alarm:
    image: alarm:1
    container_name: alarm
    