version: '3'
services:
  server:
    image: main:1.1
    container_name: flask-app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_ENV=development
    restart: always
  alarm:
    image: alarm:1.1
    container_name: alarm
    environment:
      - TELEGRAMM_TOKEN=${TELEGRAMM_TOKEN:-''}
    depends_on:
      - server
    volumes:
      - /srv/graf:/mnt
    restart: always
  # analytics:
  #   image: analytics:1
  #   container_name: analytics
  #   depends_on:
  #     - server
      # restart: always
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /stv/grafana:/var/lib/grafana

  # victoria:
  #   image: victoriametrics/victoria-metrics
  #   container_name: victoria
  #   ports:
  #     - 8428:8428
  #   volumes:
  #     - /srv/victoria:/victoria-metrics-data